### ISSUE TITLE
Add non SSL nginx.conf

### ISSUE THREAD

**Issue by Dan904** [Dan904/pl_nginx#22]
Make a second nginx.conf for non-ssl websites. Easy to switch to the other.

**Comment by mateenh** [comment]
# Steps to disable SSL on Nginx (nginx.conf)

## Comment out this section in nginx.conf:

```
    map $scheme $fastcgi_https {        Detect when HTTPS is used.
          default               off;
          https                 on;
         }

```

## Comment out this line under server block (right under server_name):

`return                  301 http://$host$request_uri;`

## Under 443 block, uncomment out these lines:

```
        ssl_certificate "/etc/letsencrypt/live/www.plutopro.xyz/fullchain.pem";
        ssl_certificate_key "/etc/letsencrypt/live/www.plutopro.xyz/privkey.pem";
    ssl_ciphers (the first one -- there's two right now)
```
