### ISSUE TITLE
v6.4.1

### ISSUE THREAD

**Issue by Dan904** [Dan904/pl_nginx#38]
fix NP
auto_prepnd 
http2

**Comment by mateenh** [comment]
This needs to go in the new .ini file (/etc/php-7.0.ini):

Search for auto_prepend_file add this:

`auto_prepend_file = '/var/www/html/wordfence-waf.php'`

**Comment by Dan904** [comment]
symlink .bash_profile to root home dir

**Comment by Dan904** [comment]
add sudo to ad-down.sh
